#!/bin/sh

export ARCH=arm
export CROSS_COMPILE=arm-none-linux-gnueabi-
export PATH=/opt/arm-2009q3/bin:$PATH

INSTALL_BINDIR=../../images
UBOOT_IMAGE=u-boot.bin
 
{
CPU_JOB_NUM=$(grep processor /proc/cpuinfo | awk '{field=$NF};END{print field+2}')
START_TIME=`date +%s`

case "$1" in
clean)
    echo make -j$CPU_JOB_NUM mrproper
    make -j$CPU_JOB_NUM mrproper
    ;;
config)
    echo make -j$CPU_JOB_NUM mango2450_config
    make -j$CPU_JOB_NUM mango2450_config
    ;;
all|*)
    echo make -j$CPU_JOB_NUM
    make -j$CPU_JOB_NUM
    if [ $? != 0 ] ; then
	    exit 1
    fi
    if [ "$2" ] ; then
        INSTALL_BINDIR=$2
    fi
    if [ $INSTALL_BINDIR ] ; then
        echo cp -a $UBOOT_IMAGE $INSTALL_BINDIR/$UBOOT_IMAGE
        cp -a $UBOOT_IMAGE $INSTALL_BINDIR/$UBOOT_IMAGE
	cp -f $UBOOT_IMAGE   ../../sdwriter/u-boot.bin
    fi
    ;;
esac

END_TIME=`date +%s`
echo "Total compile time is $((($END_TIME-$START_TIME)/60)) minutes $((($END_TIME-$START_TIME)%60)) seconds"
} 2>&1 |tee b.out
