#!/bin/sh
TOOLCHAINPATH=/opt/arm-2014.05/bin
export ARCH=armv5t
#export CROSS_COMPILE=arm-none-linux-gnueabi-
export CROSS_COMPILE=${TOOLCHAINPATH}/arm-none-linux-gnueabi-

INSTALL_BINDIR=/tftpboot/synergy2416/images
UBOOT_IMAGE=u-boot.bin
 
{
CPU_JOB_NUM=$(grep processor /proc/cpuinfo | awk '{field=$NF};END{print field+2}')
START_TIME=`date +%s`

case "$1" in
clean)
    echo make -j$CPU_JOB_NUM mrproper
    make -j$CPU_JOB_NUM mrproper
    rm *.out	
    ;;
config)
    echo make -j$CPU_JOB_NUM synergy2416_config
    make -j$CPU_JOB_NUM synergy2416_config
    ;;
all|*)
    echo make -j$CPU_JOB_NUM
    make CROSS_COMPILE=${CROSS_COMPILE} -j$CPU_JOB_NUM
    if [ $? != 0 ] ; then
	    exit 1
    fi
    if [ "$2" ] ; then
        INSTALL_BINDIR=$2
    fi
    if [ $INSTALL_BINDIR ] ; then
        echo cp -a $UBOOT_IMAGE $INSTALL_BINDIR/$UBOOT_IMAGE
        cp -a $UBOOT_IMAGE $INSTALL_BINDIR/$UBOOT_IMAGE
	#cp -f $UBOOT_IMAGE   ../../sdwriter/u-boot.bin
    fi
    ;;
esac

END_TIME=`date +%s`
echo "Total compile time is $((($END_TIME-$START_TIME)/60)) minutes $((($END_TIME-$START_TIME)%60)) seconds"
} 2>&1 |tee b.out
